sudo: required
dist: trusty

language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

install:
    - travis_retry composer self-update
    - travis_retry composer clear-cache
    - composer config -g github-oauth.github.com $GITHUB_TOKEN
    - composer create-project laravel/laravel
    - cd ./laravel
    - composer config repositories.laraedit vcs https://github.com/laraedit/laraedit.git
    - composer require laraedit/laraedit dev-master
    - composer update
    - cd ./vendor/laraedit/laraedit

script: phpunit
